import { homedir } from 'node:os'
import { join } from 'node:path'
import { toRegisterPathError } from '../error'
import { absoluteConfigPath, readConfig, writeConfig } from '../file'
import type { RegisterPathOptions, RegisterPathResult } from '../types'

function needsSnippet(content: string, snippet: string, name: string) {
  if (!content) return true
  if (content.replaceAll('\r\n', '\n').replace(/\n$/, '') === snippet) return false
  throw new Error(`The fish configuration file for ${name} is already in use`)
}

export async function registerFishPath(
  directory: string,
  options: RegisterPathOptions,
): Promise<RegisterPathResult> {
  const config = absoluteConfigPath(process.env.XDG_CONFIG_HOME || join(homedir(), '.config'))
  const path = join(config, 'fish', 'conf.d', `register-path-${options.name}.fish`)
  const quoted = `'${directory.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`
  const snippet = `# Generated by register-path for ${options.name}.\n# Do not edit manually.\n\nif not contains -- ${quoted} $PATH\n  set -gx PATH $PATH ${quoted}\nend`
  try {
    if (!needsSnippet(await readConfig(path), snippet, options.name))
      return { path, status: 'unchanged' }
    if (options.beforeWrite) {
      if ((await options.beforeWrite({ path })) !== true) return { path, status: 'skipped' }
      // beforeWrite may perform file I/O or wait for user input; re-read and check its latest contents.
      if (!needsSnippet(await readConfig(path), snippet, options.name))
        return { path, status: 'unchanged' }
    }
    await writeConfig(path, `${snippet}\n`)
    return { path, status: 'added' }
  } catch (cause) {
    throw toRegisterPathError(cause, path)
  }
}
