import { execFile } from 'node:child_process'
import { win32 } from 'node:path'
import { promisify } from 'node:util'
import { toAddPathError } from '../error'
import type { AddPathOptions, AddPathResult } from '../types'

const execute = promisify(execFile)

export async function addWindowsPath(
  directory: string,
  options: AddPathOptions,
): Promise<AddPathResult> {
  if (directory.includes(';')) throw new TypeError('directory must not contain the PATH separator')
  if (!/^(?:[a-z]:[\\/]|\\\\[^\\/]+[\\/][^\\/]+)/i.test(directory)) {
    throw new TypeError('directory must be an absolute path')
  }
  if (/[%"<>|?*]/.test(directory))
    throw new TypeError('directory contains unsupported Windows path characters')
  directory = win32.normalize(directory)
  try {
    if (options.beforeWrite) {
      const existing = await windowsPath(directory, false)
      if (existing.status === 'unchanged') return existing
      if ((await options.beforeWrite({})) !== true) return { status: 'skipped' }
    }
    // The write operation reads and checks again: beforeWrite may have changed the registry.
    return await windowsPath(directory, true)
  } catch (cause) {
    throw toAddPathError(cause)
  }
}

export async function runPowerShell(script: string) {
  const executable = win32.join(
    process.env.SystemRoot || 'C:\\Windows',
    'System32',
    'WindowsPowerShell',
    'v1.0',
    'powershell.exe',
  )
  const { stdout } = await execute(
    executable,
    [
      '-NoLogo',
      '-NoProfile',
      '-NonInteractive',
      '-EncodedCommand',
      Buffer.from(
        `[Console]::OutputEncoding = New-Object System.Text.UTF8Encoding($false)\n${script}`,
        'utf16le',
      ).toString('base64'),
    ],
    { windowsHide: true, timeout: 30_000, maxBuffer: 1024 * 1024 },
  )
  return stdout.trim()
}

// PATH handling follows Add-Path in uv's Windows installer, generated by cargo-dist:
// https://astral.sh/uv/install.ps1
// This includes reading unexpanded values and notifying Windows through a temporary variable.
export async function windowsPath(directory: string, write: boolean, key = 'Environment') {
  const payload = Buffer.from(JSON.stringify({ directory, write, key }), 'utf8').toString('base64')
  const script = String.raw`
$ErrorActionPreference = 'Stop'
$request = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${payload}')) | ConvertFrom-Json
$registry = $null
try {
  $registry = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey($request.key, [bool] $request.write)
  $kind = [Microsoft.Win32.RegistryValueKind]::ExpandString
  $raw = $null
  if ($null -ne $registry -and $registry.GetValueNames() -contains 'Path') {
    $kind = $registry.GetValueKind('Path')
    if ($kind -ne [Microsoft.Win32.RegistryValueKind]::String -and $kind -ne [Microsoft.Win32.RegistryValueKind]::ExpandString) {
      throw 'The existing user PATH is not a string registry value'
    }
    $raw = $registry.GetValue('Path', $null, [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
  }
  $wanted = $request.directory.Replace('/', '\').TrimEnd('\')
  $present = $false
  foreach ($entry in ([string] $raw).Split(';')) {
    if ($kind -eq [Microsoft.Win32.RegistryValueKind]::ExpandString) {
      $entry = [Environment]::ExpandEnvironmentVariables($entry)
    }
    if ($entry.Trim('"').Replace('/', '\').TrimEnd('\') -ieq $wanted) { $present = $true; break }
  }
  if ($present) { @{ status = 'unchanged' } | ConvertTo-Json -Compress; exit 0 }
  if (-not $request.write) { @{ status = 'added' } | ConvertTo-Json -Compress; exit 0 }
  if ($null -eq $registry) { $registry = [Microsoft.Win32.Registry]::CurrentUser.CreateSubKey($request.key) }
  $updated = $request.directory
  if (-not [string]::IsNullOrEmpty($raw)) {
    $updated = $raw + ';' + $request.directory
  }
  $registry.SetValue('Path', $updated, $kind)
  $response = @{ status = 'added' }
  # Trigger the environment notification through .NET using a temporary user variable.
  $notification = 'add-path-' + [guid]::NewGuid().ToString()
  try {
    try { [Environment]::SetEnvironmentVariable($notification, '1', 'User') }
    finally { [Environment]::SetEnvironmentVariable($notification, $null, 'User') }
  } catch { $response.warning = 'PATH was saved, but the environment change notification failed.' }
  $response | ConvertTo-Json -Compress
} catch {
  [Console]::Error.WriteLine($_.Exception.Message)
  exit 1
} finally {
  if ($null -ne $registry) { $registry.Dispose() }
}
`
  const output = await runPowerShell(script)
  const result: { status: 'added' | 'unchanged'; warning?: string } = JSON.parse(output)
  if (!['added', 'unchanged'].includes(result.status))
    throw new Error('Invalid response from Windows registry helper')
  return result
}
