import { execFileSync } from 'node:child_process'
import { readdir, readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { describe, expect, it, vi } from 'vitest'
import { addPath } from '../src'
import { installedShells } from './helpers/shell'
import { useUnixHome } from './helpers/unix'

describe.skipIf(process.platform === 'win32')('fish-installation', () => {
  const fixture = useUnixHome('fish')
  const executable = installedShells.find(({ shell }) => shell === 'fish')?.executable

  it('labels the generated conf.d snippet and leaves it unchanged on reinstall', async () => {
    const beforeWrite = vi.fn(() => true)
    const options = { name: 'example', beforeWrite }
    const path = join(fixture.home, '.config/fish/conf.d/add-path-example.fish')
    expect(await addPath('/opt/bin', options)).toEqual({ path, status: 'added' })
    const content = await readFile(path, 'utf8')
    expect(content).toBe(
      "# Generated by add-path for example.\n# Do not edit manually.\n\nif not contains -- '/opt/bin' $PATH\n  set -gx PATH $PATH '/opt/bin'\nend\n",
    )
    expect(await addPath('/opt/bin', options)).toEqual({ path, status: 'unchanged' })
    expect(beforeWrite).toHaveBeenCalledOnce()
    expect(await readFile(path, 'utf8')).toBe(content)
    expect(await readdir(join(fixture.home, '.config/fish'))).toEqual(['conf.d'])
  })

  it.skipIf(!executable)('is loaded automatically by fish on startup', async () => {
    await addPath('/opt/example/bin', { name: 'example' })
    const output = execFileSync(executable as string, ['-c', 'printf "%s\\n" $PATH'], {
      encoding: 'utf8',
      env: {
        HOME: fixture.home,
        XDG_CONFIG_HOME: join(fixture.home, '.config'),
        PATH: '/usr/bin:/bin',
        LC_ALL: 'en_US.UTF-8',
      },
    })
    expect(
      output
        .trimEnd()
        .split('\n')
        .filter((entry) => entry === '/opt/example/bin'),
    ).toHaveLength(1)
  })
})
